tcp:
  routers:
    proxmox-router:
      entryPoints:
        - proxmox-tls
      rule: "HostSNI(`*`)"
      service: proxmox-service
      tls: passthrough

  services:
    proxmox-service:
      loadBalancer:
        servers:
          - address: "192.168.1.101:8006"
